server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: menu
          uri: http://localhost:8082
          predicates:
            - Path=/menuGroups/**, /menus/**, 
        - id: basic
          uri: http://localhost:8083
          predicates:
            - Path=/products/**, 
        - id: order
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: menu
          uri: http://menu:8080
          predicates:
            - Path=/menuGroups/**, /menus/**, 
        - id: basic
          uri: http://basic:8080
          predicates:
            - Path=/products/**, 
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
